pub mod systems;
pub mod planets;
pub mod settlements;
pub mod stations;
pub mod space_elevator;
pub mod connections;
pub mod players;
pub mod ships;
pub mod market;
pub mod trucking;
pub mod construction;
pub mod leaderboard;
pub mod trade;
pub mod economy;
pub mod persistence;

pub use systems::{admin_systems_router, player_systems_router};
pub use planets::{admin_planets_router, player_planets_router};
pub use settlements::{admin_settlements_router, player_settlements_router};
pub use stations::{admin_stations_router, player_stations_router};
pub use space_elevator::space_elevator_router;
pub use connections::admin_connections_router;
pub use players::{admin_players_router, player_players_router};
pub use ships::player_ships_router;
pub use market::player_market_router;
pub use trucking::player_trucking_router;
pub use construction::player_projects_router;
pub use leaderboard::player_leaderboard_router;
pub use trade::player_trade_router;
pub use economy::player_economy_router;
pub use persistence::admin_persistence_router;
